### ISSUE TITLE
SOLVED ***Cannot get SCROLL_WHEEL function to work

### ISSUE THREAD

**Issue by brabs27** [Electronicks/JoyShockMapper#141]
Hello, I am trying to get scroll wheel to work on my right stick. (Using rotation)
I’ve tried L,RIGHT_STICK _MODE = SCROLL_WHEEL.
This doesn’t work, what am I doing wrong?

**Comment by Jazztache** [comment]
Just verified this works. SCROLL_WHEEL lets you bind stuff to LLEFT and LRIGHT (or RLEFT and RRIGHT)
Try this:

```
L,RIGHT_STICK_MODE = SCROLL_WHEEL
RLEFT = SCROLLUP
RRIGHT = SCROLLDOWN
```

A cool effect of this, is that you can use sticks as a scrollwheel to step through YouTube videos frame-by-frame like this:

```
LEFT_STICK_MODE = SCROLL_WHEEL
LLEFT = ,
LRIGHT = .
```
or
```
RIGHT_STICK_MODE = SCROLL_WHEEL
RLEFT = ,
RRIGHT = .
```

Side note: Not sure if it works with the motion stick without conflicting with gyro, might try it later.
Also, thanks for pointing out that the stick modes work with modeshift, didn't think that would be the case.

I found it in `3. Stick Configuration` of the manual:
> SCROLL_WHEEL: enable left and right bindings by rotating the stick counter-clockwise or clockwise.
Every 30 degrees you rotate the stick clockwise, the RRIGHT binding fires. Every 30 degrees you rotate the stick counter-clockwise, the RLEFT binding fires. I figured out it was 30 degrees *today* due to the `leftover is now *blah*` messages that JSM spams.

Hope this helps!

**Comment by brabs27** [comment]
Thanks Jazztache!
That worked! It must have been the RLEFT and RRIGHT Bits that were needed.
I’m glad I was able to show you something with the modifier too
Thanks again!

**Comment by Jazztache** [comment]
No problem, put a [SOLVED] at the front of the title and close the issue. Hopefully search engines index this :)
