### ISSUE TITLE
DualSense Haptics and Adaptive Triggers do not function properly

### ISSUE THREAD

**Issue by Woedenaz** [Electronicks/JoyShockMapper#18]
I imagine this is more due to the fact that these aren't entirely supported on PC yet, but this program gets the closest I've seen to actually getting these to work.

I've spent the last couple days trying to get the DualSense to work on ScarletNexus, which has both Haptics and Adaptive Trigger support on the PS5. When using JoyShockMapper with a custom Autoload file, I can get it to recognize that there is Rumble and the Adaptive Triggers seem to turn on. However, the Rumble is binary (either on or off, no haptics) and the Adaptive Triggers seem to be stuck at a single resistive strength.

I went and tried the Demo on the PS5 to make sure and it does appear that it's not quite right. I'd be interested in seeing if this can be fixed or not. I'm not really sure if SDL2 even has support for this yet but perhaps one day down the line it will.

Here is the /autoload ScarletNexus-Win64-Shipping.txt file that I am using (it's basically just the DS4 one found in GyroConfigs):

```
# This configuration file will map a virtual ds4 controller for each connected controller.
RESET_MAPPINGS
VIRTUAL_CONTROLLER = DS4
RUMBLE = ON
ADAPTIVE_TRIGGER = ON

UP = PS_UP
DOWN = PS_DOWN
LEFT = PS_LEFT
RIGHT = PS_RIGHT
L = PS_L1
R = PS_R1
W = PS_SQUARE
S = PS_CROSS
N = PS_TRIANGLE
E = PS_CIRCLE
L3 = PS_L3
R3 = PS_R3
- = PS_SHARE
+ = PS_OPTIONS
HOME = PS_HOME
CAPTURE = PS_PAD_CLICK
ZL_MODE = PS_L2
ZR_MODE = PS_R2
LEFT_STICK_MODE = LEFT_STICK
RIGHT_STICK_MODE = RIGHT_STICK
```

**Comment by BraqueDown** [comment]
The game isn't treating your controller as a native Dualsense because you're emulating a Dualshock 4.

What JSM's Adaptive Trigger implementation actually does (I think) is add resistance when using Dual Stage Trigger mappings. It can't magically add PS5 feature support to PC ports that don't implement them.

**Comment by AmyLucyRose** [comment]
It is possible that the PC version of Scarlett Nexus doesn’t even send the Adaptive Trigger and Haptics data in the first place, since these features aren’t supported on PC.
However, the DualSense seems to use sound for haptics, so a more advanced version of it could very well be implemented in JSM. I don’t know if using the headset port works when using Bluetooth, but if it does, then that’s already more than halfway there for haptics.

**Comment by Electronicks** [comment]
Regarding adaptive triggers: the support present in ps5 games are absent in PC games. The only PC game I know of that supports adaptive trigger is Metro Exodus Enhanced Edition (not regular). JSM does use adaptive triggers however, but cannot be aware of game states. JSM will play with the trigger resistance depending on the dual stage trigger mode chosen.

Regarding haptic feedback: JSM forwards legacy rumble data, it doesn't make use of the fine haptics (yet). It's not clear whether forwarding the speaker sounds directly to the haptics will lead to a good experience either. It would be more useful to highlight control scheme events like holds, or touchpad feedback.

There is more information on the Adaptive Trigger implementation in the README.
