### ISSUE TITLE
Instant (!) Action Modifier not functioning correctly

### ISSUE THREAD

**Issue by BraqueDown** [Electronicks/JoyShockMapper#7]
When trying to use the Instant (!) modifier for a normal binding, rather than performing an instant press, it simply behaves like a regular press.

Result with `R = !W`:

https://user-images.githubusercontent.com/43602802/119801710-4f49e180-bf21-11eb-904a-b6b8cf1c689f.mp4

More puzzlingly, trying to use Instant for a release press, it instead toggles the binding, and unlike a normal Toggle, pressing the button again does not remove the toggle.

Result with `R = !W/`:

https://user-images.githubusercontent.com/43602802/119802405-da2adc00-bf21-11eb-9186-ebc0026fbfb5.mp4

**Comment by Electronicks** [comment]
Thank you for your report. There is indeed a bug with instant presses. I've found the issue and will issue a release with it soon. It seems the bug was introduce as part of a previous bugfix for turbo presses not releasing (fixing the latter broke the former... -,- ).
This is the kind of thing unit tests should be able to prevent once I get around writing those.

Thanks @BraqueDown!

**Comment by Electronicks** [comment]
Fixed in v3.1.1
